- name:  add line into sudoers using lineinfile with insertafter 
  hosts: localhost
  tasks:
    - name: add line in sudoers file 
      lineinfile:
        path: /etc/sudoers
        state: absent      
        line: "suresh ALL=(ALL)  ALL" 
        validate: 'visudo -cf %s'
