- name: Create a new primary partition for LVM
  community.general.parted:
    device: /dev/sdb
    number: 1
    flags: [ lvm ]
    state: present
    #part_start: 1GiB
    #part_end: 10GiB or "100%" 

- name: Format the disk 
  filesystem:
    fs_type: ext4
    dev: "/dev/{{ raw_disks }}"	

