- name: create a file with content using varibles
  hosts: all
  become: true
  tasks:
    - name: create multiple directory
      file:
       dest: "/tmp{{ item }}"
       state: directory
       mode: 755
       owner: ec2-user
       group: ec2-user
      loop:
       - dev1
       - dev2
       - dev3
         
