- name: Patching
  hosts: all
  become: true
  tasks:
    - name: check  security patch updates
      shell: "yum --security check-update"
      register: shell_output
    - debug:
        msg: "{{shell_output.stdout}}"
# Patching  only security updates and exclude kernerl
    - name: patching only security updates and exclude kernel
      shell: "yum update --security --exculde=kernel*"
      register : shell_output
    - debug:
        msg: "{{shell_output.stdout}}"

# Patching all  updates and exclude kernerl
    - name: patching only security updates and exclude kernel
      shell: "yum update  --exculde=kernel*"
      register : shell_output
    - debug:
        msg: "{{shell_output.stdout}}"



 