##Creating   the username, password    and sudo access using ansible
- name: adding the line in the /etc/sudoers
  hosts: localhost
  tasks:
        
    - name: Add a line to a file if the file does not exist, without passing regexp
      lineinfile:
        path: /etc/sudoers
        regexp: '^root    ALL=(ALL)       ALL'
        line: dhanapal.ikt333    ALL=(ALL)       ALL
        create: yes
        
