###Log file location############
The different types of log files and their locations :
/var/log/messages -----> System and general messages and DHCP log messages.
/var/log/authlog -----> Authentication log messages.
/var/log/secure -----> Security and authentication and user log messages.
/var/log/maillog -----> Mail server log messages.
/var/log/cron -----> Cron jobs log messages.
/var/log/boot.log -----> All booting log messages.
/var/log/httpd -----> All Apache web server log messages.
/var/log/mysqld.log -----> Mysql database server log messages.
/var/log/utmp or /var/log/wtmp -----> All the users login messages.
/var/log/Qmail -----> Qmail log messages.
/var/log/kernel.log -----> All kernel related log messages.
/var/log/samba -----> All samba server log messages.
/var/log/anakonda.log -----> Linux installation log messages.
/var/log/lastlog -----> Recent login information for all users.
# lastlog (to see the log messages of the above log  file)
/var/log/yum.log -----> All package installation log messages generated by # yum or # rpm commands.
/var/log/cups -----> All printer and printing related log messages.
/var/log/ntpstat -----> All ntp server and services log messages.
/var/log/spooler -----> Mail, printer and cron jobs spooling messages.
/var/log/sssd -----> System security service deamon log messages.
/var/log/audit.log -----> SELinux log messages.
# dmesg (to see the boot log messages)
# tailf or # tail -f /var/log/secure (to check or watch the log files  continuously)
# vim /etc/rsyslog.conf (we can change the log messages default  destinations)
* Whenever we change the contents of the /etc/rsyslog.conf file, then we have to restart the rsyslog service.
* There are 7 types of priority messages. We can change the default destination of those log files. For  that open rsyslog server configuration file and we have enter the rules as follows.
# vim /etc/rsyslog.conf
<priority type> . <priority name> <new destination of the log files> (save and exit this file)
# logger <type any text> (to send that text into /var/log/messages files and to test  whether logging service is running or not)
# logrotate (to create the log files with datewise)
* Generally in log messages the fields are,Date & Time : From which system : command name or change : 
Execution of the command
# yum install tmpwatch -y (to install the tmpwatchpackage to execute the below command)
# tmpwatch (to monitor the /tmp directory)
# logwatch (to monitor the log messages)
# yum install watch -y (to install the watch package to execute the below command)
# watch <command> (to watch the specified command results continuously)
# mkdir mode=755 /ram (to give the permissions to the directory while creating that directory)
# journalctl (it tracks all the log files between two different timings and save by default in /run/log location)
* /run/log is mounted on tmpfs file system ie., if the system is rebooted the whole information in that location will be deleted or erased
