---
# tasks file for raid1_lvm_configuration
- import_tasks: raid1_configuration.yml
- import_tasks: create_directory_mountpoint.yml
- import_tasks: new_partition.yml
- import_tasks: lvm_creation.yml
